# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Timer_Project/Timer_Project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project || ORIG_REF_NAME==Timer_Project} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_microblaze_0_0/Timer_Project_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_microblaze_0_0 || ORIG_REF_NAME==Timer_Project_microblaze_0_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_dlmb_v10_0/Timer_Project_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_dlmb_v10_0 || ORIG_REF_NAME==Timer_Project_dlmb_v10_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_ilmb_v10_0/Timer_Project_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_ilmb_v10_0 || ORIG_REF_NAME==Timer_Project_ilmb_v10_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_dlmb_bram_if_cntlr_0/Timer_Project_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Timer_Project_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_ilmb_bram_if_cntlr_0/Timer_Project_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Timer_Project_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_lmb_bram_0/Timer_Project_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_lmb_bram_0 || ORIG_REF_NAME==Timer_Project_lmb_bram_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_xbar_0/Timer_Project_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_xbar_0 || ORIG_REF_NAME==Timer_Project_xbar_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_microblaze_0_axi_periph_0/Timer_Project_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Timer_Project_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_microblaze_0_axi_intc_0/Timer_Project_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Timer_Project_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_microblaze_0_xlconcat_0/Timer_Project_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Timer_Project_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_mdm_1_0/Timer_Project_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_mdm_1_0 || ORIG_REF_NAME==Timer_Project_mdm_1_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_clk_wiz_1_0/Timer_Project_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_clk_wiz_1_0 || ORIG_REF_NAME==Timer_Project_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_rst_clk_wiz_1_100M_0/Timer_Project_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Timer_Project_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Timer_Project/ip/Timer_Project_axi_uartlite_0_0/Timer_Project_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Timer_Project_axi_uartlite_0_0 || ORIG_REF_NAME==Timer_Project_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/Timer_Project/Timer_Project_ooc.xdc
