# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado_Projects/Timer_Project/Timer_Project.srcs/sources_1/bd/Timer_Project/ip/Timer_Project_ilmb_bram_if_cntlr_0/Timer_Project_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'Timer_Project_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_Projects/Timer_Project/Timer_Project.srcs/sources_1/bd/Timer_Project/ip/Timer_Project_ilmb_bram_if_cntlr_0/Timer_Project_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Timer_Project_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Vivado_Projects/Timer_Project/Timer_Project.srcs/sources_1/bd/Timer_Project/ip/Timer_Project_ilmb_bram_if_cntlr_0/Timer_Project_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'Timer_Project_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_Projects/Timer_Project/Timer_Project.srcs/sources_1/bd/Timer_Project/ip/Timer_Project_ilmb_bram_if_cntlr_0/Timer_Project_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Timer_Project_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
